from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

import groups.views as gviews

urlpatterns = [
    path('', views.teacherview, name='teacherview'),
    path('sync/<int:pk>/', views.sync_class, name='sync_class'),
    path('editclass/<int:pk>/', views.classeditview, name='classeditview'),
    path('editclass/<int:pk>/latex/', views.latexclassview, name='latexclassview'),
    path('editclass/<int:pk>/pdf/', views.class_as_pdf, name='class_as_pdf'),
    path('editclass/<int:pk>/add-unit/', views.newunitview, name='newunitview'),
    path('editclass/<int:pk>/units/<int:upk>/', views.uniteditview, name='uniteditview'),
    path('editclass/<int:pk>/units/<int:upk>/add-problemset/', views.newproblemsetview, name='newproblemsetview'),
    path('editclass/<int:pk>/units/<int:upk>/add-slides/', views.newslidesview, name='newslidesview'),
    path('editclass/<int:pk>/units/<int:upk>/add-test/', views.newtestview, name='newtestview'),
    path('editclass/<int:pk>/units/<int:upk>/problemsetlatex/<int:ppk>/', views.latexpsetview, name='latexpsetview'),
    path('editclass/<int:pk>/units/<int:upk>/newproblemsetlatex/<int:ppk>/', views.newlatexpsetview, name='newlatexpsetview'),
    path('editclass/<int:pk>/units/<int:upk>/problemsetanswerkeylatex/<int:ppk>/', views.latexpsetanswerkeyview, name='latexpsetanswerkeyview'),
    path('editclass/<int:pk>/units/<int:upk>/problemset/<int:ppk>/', views.problemseteditview, name='problemseteditview'),
    path('editclass/<int:pk>/units/<int:upk>/problemset/<int:ppk>/load-original-problem/', views.loadoriginalproblemform, name='load-original-problem'),
    path('editclass/<int:pk>/units/<int:upk>/problemset/<int:ppk>/add-original-problem/', views.addoriginalproblem, name='add-original-problem'),
    path('editclass/<int:pk>/units/<int:upk>/problemset/<int:ppk>/find-num-probs-matching-tag/', views.numprobsmatching, name='numprobsmatching'),
    path('editclass/<int:pk>/units/<int:upk>/problemset/<int:ppk>/add-tagged-problems/', views.reviewmatchingproblems, name='reviewmatchingproblems'),
    path('editclass/<int:pk>/units/<int:upk>/problemset/<int:ppk>/review-problem-group/', views.reviewproblemgroup, name='reviewproblemgroup'),
    path('editclass/<int:pk>/units/<int:upk>/problemset/<int:ppk>/edit-point-value/<int:pppk>/', views.update_point_value, name='edit-point-value'),
#    path('editclass/<int:pk>/units/<int:upk>/problemset/<int:ppk>/edit-question-type/<int:pppk>/', views.editquestiontype, name='edit-question-type'),
    path('editclass/<int:pk>/units/<int:upk>/problemset/<int:ppk>/change-qt-original-problem/', views.loadcqtoriginalproblemform, name='loadcqtoriginalproblemform'),
    path('editclass/<int:pk>/units/<int:upk>/problemset/<int:ppk>/pdf/', views.pset_as_pdf, name='pset_as_pdf'),
    path('editclass/<int:pk>/units/<int:upk>/problemset/<int:ppk>/latex/', views.pset_as_latex, name='pset_as_latex'),
    path('editclass/<int:pk>/units/<int:upk>/problemset/<int:ppk>/sol-pdf/', views.pset_sols_as_pdf, name='pset_sols_as_pdf'),
#slides
    path('editclass/<int:pk>/units/<int:upk>/slideslatex/<int:ppk>/', views.latexslidesview, name='latexslidesview'),
    path('editclass/<int:pk>/units/<int:upk>/slides/<int:spk>/', views.slideseditview, name='slideseditview'),
    path('editclass/<int:pk>/units/<int:upk>/slides/<int:spk>/add-slide/', views.newslideview, name='addslide'),
    path('editclass/<int:pk>/units/<int:upk>/slides/<int:spk>/edit-slide/<int:sspk>/', views.editslideview, name='editslideview'),
    path('editclass/<int:pk>/units/<int:upk>/slides/<int:spk>/edit-slide/<int:sspk>/edit-textblock/<int:tpk>/', login_required(views.TextBlockUpdateView.as_view()),name="update_textblock"),
    path('editclass/<int:pk>/units/<int:upk>/slides/<int:spk>/edit-slide/<int:sspk>/edit-theorem/<int:tpk>/', login_required(views.TheoremUpdateView.as_view()),name="update_theorem"),
    path('editclass/<int:pk>/units/<int:upk>/slides/<int:spk>/edit-slide/<int:sspk>/edit-proof/<int:tpk>/', login_required(views.ProofUpdateView.as_view()),name="update_proof"),
    path('editclass/<int:pk>/units/<int:upk>/slides/<int:spk>/edit-slide/<int:sspk>/load-original-problem/', views.loadoriginalexampleproblemform, name='load-original-example-problem'),
    path('editclass/<int:pk>/units/<int:upk>/slides/<int:spk>/edit-slide/<int:sspk>/exampleoriginalqt/', views.exampleoriginalqt, name='exampleoriginalqt'),
    path('editclass/<int:pk>/units/<int:upk>/slides/<int:spk>/edit-slide/<int:sspk>/exampleproblemlabel/', views.exampleproblemlabel, name='exampleproblemlabel'),
    path('editclass/<int:pk>/units/<int:upk>/slides/<int:spk>/edit-slide/<int:sspk>/example-problem-groups/', views.exampleproblemgroups, name='exampleproblemgroups'),
    path('editclass/<int:pk>/units/<int:upk>/slides/<int:spk>/edit-slide/<int:sspk>/load-problem-group/', views.exampleproblemgroupproblems, name='loadproblemgroup'),
    path('editclass/<int:pk>/units/<int:upk>/slides/<int:spk>/edit-slide/<int:sspk>/add-problem/', views.exampleaddproblem, name='exampleaddproblem'),
    path('editclass/<int:pk>/units/<int:upk>/slides/<int:spk>/edit-slide/<int:sspk>/load-bytag/', views.examplebytag, name='examplebytag'),
    path('editclass/<int:pk>/units/<int:upk>/slides/<int:spk>/edit-slide/<int:sspk>/load-problems-bytag/', views.examplebytagproblems, name='examplebytagproblems'),
    path('editclass/<int:pk>/units/<int:upk>/slides/<int:spk>/edit-slide/<int:sspk>/edit-exampleproblem/<int:sopk>/', views.editexampleproblem, name='editexampleproblem'),
    path('editclass/<int:pk>/units/<int:upk>/slides/<int:spk>/edit-slide/<int:sspk>/change-qt/', views.loadcqtexampleproblemform, name='loadcqtexampleproblemform'),
# all functions must be added...unless consolidation.
    path('editclass/<int:pk>/units/<int:upk>/test/<int:tpk>/', views.testeditview, name='testeditview'),
    path('editclass/<int:pk>/units/<int:upk>/test/<int:ppk>/load-original-problem/', views.testloadoriginalproblemform, name='test-load-original-problem'),
    path('editclass/<int:pk>/units/<int:upk>/test/<int:ppk>/add-original-problem/', views.testaddoriginalproblem, name='testadd-original-problem'),
    path('editclass/<int:pk>/units/<int:upk>/test/<int:ppk>/find-num-probs-matching-tag/', views.testnumprobsmatching, name='testnumprobsmatching'),
    path('editclass/<int:pk>/units/<int:upk>/test/<int:ppk>/add-tagged-problems/', views.testreviewmatchingproblems, name='testreviewmatchingproblems'),
    path('editclass/<int:pk>/units/<int:upk>/test/<int:ppk>/review-problem-group/', views.testreviewproblemgroup, name='testreviewproblemgroup'),
    path('editclass/<int:pk>/units/<int:upk>/test/<int:ppk>/edit-point-value/<int:pppk>/', views.testupdate_point_value, name='testedit-point-value'),
    path('editclass/<int:pk>/units/<int:upk>/test/<int:ppk>/edit-blank-point-value/<int:pppk>/', views.testupdate_blank_value, name='testedit-blank-value'),
#    path('editclass/<int:pk>/units/<int:upk>/test/<int:ppk>/edit-question-type/<int:pppk>/', views.testeditquestiontype, name='testedit-question-type'),
    path('editclass/<int:pk>/units/<int:upk>/test/<int:ppk>/change-qt-original-problem/', views.testloadcqtoriginalproblemform, name='testloadcqtoriginalproblemform'),

#problemgroups
    path('mystudents/', views.studentmanager, name='studentmanager'),
    path('mystudents/<str:username>/', views.studentclassview, name='studentclassview'),
    path('mystudents/<str:username>/problemset/<int:upk>/', views.studentproblemsetview, name='studentproblemsetview'),
    path('mystudents/<str:username>/problemset/<int:upk>/load_grade/', views.load_grade, name='load_grade'),
    path('mystudents/<str:username>/problemset/<int:upk>/save_grade/', views.save_grade, name='save_grade'),
    path('mystudents/<str:username>/problemset/<int:upk>/load_sol/<int:ppk>/', login_required(views.SolutionView.as_view()), name='teacher_load_solution'),
    path('mystudents/<str:username>/slides/<int:uspk>/', views.slidesview, name='userslidesview'),
    path('publishclass/<int:pk>/', views.publishview, name='publishview'),
    path('class/<int:pk>/', views.currentclassview, name='currentclass'),
    path('class/<int:pk>/roster/', views.rosterview, name='rosterview'),
    path('class/<int:pk>/roster/assignment/<int:ppk>/', views.assignmentview, name='assignmentview'),
    path('class/<int:pk>/roster/get-student-list/', views.getstudentlist, name='getstudentlist'),
    path('class/<int:pk>/roster/add-student/', views.addstudenttoclass, name='addstudent'),
    path('class/<int:pk>/roster/<str:username>/', views.studentoneclassview, name='studentoneclassview'),
    path('class/<int:pk>/roster/<str:username>/problemset/<int:upk>/', views.studentproblemsetview, name='studentproblemsetview2'),
    path('class/<int:pk>/roster/<str:username>/problemset/<int:upk>/load_grade/', views.load_grade, name='load_grade2'),
    path('class/<int:pk>/roster/<str:username>/problemset/<int:upk>/save_grade/', views.save_grade, name='save_grade2'),
    path('class/<int:pk>/roster/<str:username>/problemset/<int:upk>/load_sol/<int:ppk>/', login_required(views.SolutionView.as_view()), name='teacher_load_solution2'),
    path('class/<int:pk>/slides/<int:spk>/', views.slidesview, name='slidesview'),
    path('class/<int:pk>/problemset/<int:pspk>/', views.teacherproblemsetview, name='teacherproblemsetview'),
    path('class/<int:pk>/problemset/<int:pspk>/load_sol/<int:ppk>/', login_required(views.SolutionView.as_view()), name='teacher_load_solution2'),
    path('class/<int:pk>/problemset/<int:pspk>/blind/<int:popk>/', views.blindgrade, name='blindgradingview'),
    path('class/<int:pk>/problemset/<int:pspk>/blind/<int:popk>/load_grade/', views.load_grade, name='blindloadgrade'),
    path('class/<int:pk>/problemset/<int:pspk>/blind/<int:popk>/save_grade/', views.save_grade, name='blindsavegrade'),
    path('class/<int:pk>/problemset/<int:pspk>/blind/<int:popk>/change_grade/', views.change_grade, name='blindchangegrade'),
    path('class/<int:pk>/problemset/<int:pspk>/alpha/<int:popk>/', views.alphagrade, name='alphagradingview'),
    path('class/<int:pk>/problemset/<int:pspk>/alpha/<int:popk>/load_grade/', views.load_grade, name='alphaloadgrade'),
    path('class/<int:pk>/problemset/<int:pspk>/alpha/<int:popk>/save_grade/', views.save_grade, name='alphasavegrade'),
    path('class/<int:pk>/problemset/<int:pspk>/alpha/<int:popk>/change_grade/', views.change_grade, name='alphachangegrade'),
    path('class/<int:pk>/test/<int:tpk>/', views.teachertestview, name='teachertestview'),
    path('class/<int:pk>/test/<int:tpk>/load_sol/<int:ppk>/', login_required(views.SolutionView.as_view()), name='teacher_load_solution3'),
##^^Needs basically the same stuff as problemset,but need to decide if new response environment needed first...^^##
    path('migrate_response/<str:username>/<int:npk>/',views.migrate_response,name="migrate_response"),
    path('migrate_response/<str:username>/<int:npk>/add_response/',views.move_response,name="move_response"),
    path('ajax/load-edit-duedate/',views.load_edit_duedate, name="load_edit_duedate"),
    path('ajax/save-duedate/',views.save_duedate, name="save_duedate"),
    path('ajax/delete-duedate/',views.delete_duedate, name="delete_duedate"),
    path('ajax/load-edit-startdate/',views.load_edit_startdate, name="load_edit_startdate"),
    path('ajax/save-startdate/',views.save_startdate, name="save_startdate"),
    path('ajax/delete-startdate/',views.delete_startdate, name="delete_startdate"),
    path('ajax/load-edit-timelimit/',views.load_edit_timelimit, name="load_edit_timelimit"),
    path('ajax/save-timelimit/',views.save_timelimit, name="save_timelimit"),
    path('ajax/delete-timelimit/',views.delete_timelimit, name="delete_timelimit"),
    path('ajax/export-pset-to-group/',views.export_pset_to_group, name="export_pset_to_group"),
    path('ajax/problemobject/load-edit-questiontype/',views.loadeditquestiontype, name="po_load_edit_qt"),
    path('ajax/problemobject/load-new-sol/',views.load_new_solution_form, name="class_load_new_solution_form"),
    path('ajax/problemobject/save-new-sol/',views.save_new_solution, name="class_save_new_solution"),
    path('ajax/problemobject/load-view-sols/',views.load_manage_solutions, name="class_load_manage_solutions"),
    path('ajax/problemobject/display-sol/',views.display_solution, name="class_display_solution"),
    path('ajax/problemobject/undisplay-sol/',views.undisplay_solution, name="class_undisplay_solution"),
    path('ajax/problemobject/delete-sol/',views.delete_solution, name="class_delete_solution"),
    path('ajax/problemobject/edit-sol/',views.load_edit_sol, name="class_load_edit_solution"),
    path('ajax/problemobject/save-edited-sol/',views.save_edited_solution, name="class_save_edited_solution"),
    path('ajax/problemobject/move-problem/',views.move_problem, name="move_prob"),
    path('ajax/problemobject/copy-problem/',views.copy_problem, name="copy_prob"),

    path('ajax/edit-class-name/',views.editclassname, name="editclassname"),
    path('ajax/save-class-name/',views.saveclassname, name="saveclassname"),
    path('ajax/edit-unit-name/',views.editunitname, name="editunitname"),
    path('ajax/save-unit-name/',views.saveunitname, name="saveunitname"),
    path('ajax/edit-problemset-name/',views.editproblemsetname, name="editproblemsetname"),
    path('ajax/save-problemset-name/',views.saveproblemsetname, name="saveproblemsetname"),
    path('ajax/edit-test-name/',views.edittestname, name="edittestname"),
    path('ajax/save-test-name/',views.savetestname, name="savetestname"),
    path('ajax/edit-slidegroup-name/',views.editslidegroupname, name="editslidegroupname"),
    path('ajax/save-slidegroup-name/',views.saveslidegroupname, name="saveslidegroupname"),
    path('ajax/edit-slide-title/',views.editslidetitle, name="editslidetitle"),
    path('ajax/save-slide-title/',views.saveslidetitle, name="saveslidetitle"),

    path('ajax/edit-sharing/', views.load_sharing_modal, name='class_edit_sharing'),
    path('ajax/share-with-user/', views.share_with_user, name='class_share_with_user'),
    path('ajax/change-permission/', views.change_permission, name='class_change_permission'),
    path('ajax/confirm-delete-class/', views.confirm_delete_class, name='confirm_delete_class'),
    path('ajax/confirm-remove-class/', views.confirm_remove_class, name='confirm_remove_class'),
    path('ajax/delete-class/', views.delete_class, name='delete_class'),
    path('ajax/remove-class/', views.remove_class, name='remove_class'),
#    path('edit/<int:pk>/edit_section/<int:spk>/', login_required(views.SectionUpdateView.as_view()),name="update_section"),
#    path('edit/<int:pk>/edit_subsection/<int:spk>/', login_required(views.SubsectionUpdateView.as_view()),name="update_subsection"),
#    path('edit/<int:pk>/edit_textblock/<int:spk>/', login_required(views.TextBlockUpdateView.as_view()),name="update_textblock"),
#    path('edit/<int:pk>/edit_theorem/<int:spk>/', login_required(views.TheoremUpdateView.as_view()),name="update_theorem"),
#    path('edit/<int:pk>/edit_proof/<int:spk>/', login_required(views.ProofUpdateView.as_view()),name="update_proof"),
#    path('edit/<int:pk>/edit_handout/', login_required(views.HandoutUpdateView.as_view()),name="update_handout"),

#    path('edit/<int:pk>/editnewtest/<int:hpk>/', views.editnewtestview, name='h_editnewtestview'),
]
