# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-07 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20170926_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemobject',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='exampleproblem',
            name='problem_number',
        ),
        migrations.RemoveField(
            model_name='theorem',
            name='theorem_number',
        ),
        migrations.AddField(
            model_name='slide',
            name='top_order_number',
            field=models.IntegerField(default=0),
        ),
    ]
