# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-09 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampleproblem',
            name='mc_answer',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='exampleproblem',
            name='sa_answer',
            field=models.CharField(default='', max_length=20),
        ),
    ]
