# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-09 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20171009_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampleproblem',
            name='prefix',
            field=models.CharField(default='', max_length=20),
        ),
    ]
