# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-12 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20171010_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publishedclass',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
