# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-12 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20171011_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='num_problems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publishedclass',
            name='num_problems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='num_problems',
            field=models.IntegerField(default=0),
        ),
    ]
