# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-21 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_auto_20171011_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidegroup',
            name='num_slides',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='num_problemsets',
            field=models.IntegerField(default=0),
        ),
    ]
