# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-22 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_auto_20171021_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitobject',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='unitobject',
            name='object_id',
        ),
        migrations.AddField(
            model_name='problemset',
            name='unit_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.UnitObject'),
        ),
        migrations.AddField(
            model_name='slidegroup',
            name='unit_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.UnitObject'),
        ),
    ]
