# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-01 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_auto_20171022_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedclass',
            name='parent_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Class'),
        ),
    ]
