# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-01 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_publishedclass_parent_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampleproblem',
            name='is_published',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='exampleproblem',
            name='parent_exampleproblem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.ExampleProblem'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='is_published',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='parent_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.ImageModel'),
        ),
        migrations.AddField(
            model_name='problemobject',
            name='is_published',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='problemobject',
            name='parent_problemobject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.ProblemObject'),
        ),
        migrations.AddField(
            model_name='problemset',
            name='is_published',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='problemset',
            name='parent_problemset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.ProblemSet'),
        ),
        migrations.AddField(
            model_name='proof',
            name='is_published',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='proof',
            name='parent_proof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Proof'),
        ),
        migrations.AddField(
            model_name='slide',
            name='is_published',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='slide',
            name='parent_slide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Slide'),
        ),
        migrations.AddField(
            model_name='slidegroup',
            name='is_published',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='slidegroup',
            name='parent_slidegroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.SlideGroup'),
        ),
        migrations.AddField(
            model_name='slideobject',
            name='is_published',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='slideobject',
            name='parent_slideobject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.SlideObject'),
        ),
        migrations.AddField(
            model_name='textblock',
            name='is_published',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='textblock',
            name='parent_textblock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.TextBlock'),
        ),
        migrations.AddField(
            model_name='theorem',
            name='is_published',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='theorem',
            name='parent_theorem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Theorem'),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_published',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='parent_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Unit'),
        ),
        migrations.AddField(
            model_name='unitobject',
            name='is_published',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='unitobject',
            name='parent_unitobject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.UnitObject'),
        ),
        migrations.AlterField(
            model_name='publishedclass',
            name='parent_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Class'),
        ),
    ]
