# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-02 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_auto_20171102_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampleproblem',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='exampleproblem',
            name='parent_exampleproblem',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='parent_image',
        ),
        migrations.RemoveField(
            model_name='problemobject',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='problemobject',
            name='parent_problemobject',
        ),
        migrations.RemoveField(
            model_name='problemset',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='problemset',
            name='parent_problemset',
        ),
        migrations.RemoveField(
            model_name='proof',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='proof',
            name='parent_proof',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='parent_slide',
        ),
        migrations.RemoveField(
            model_name='slidegroup',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='slidegroup',
            name='parent_slidegroup',
        ),
        migrations.RemoveField(
            model_name='slideobject',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='slideobject',
            name='parent_slideobject',
        ),
        migrations.RemoveField(
            model_name='textblock',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='textblock',
            name='parent_textblock',
        ),
        migrations.RemoveField(
            model_name='theorem',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='theorem',
            name='parent_theorem',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='parent_unit',
        ),
        migrations.RemoveField(
            model_name='unitobject',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='unitobject',
            name='parent_unitobject',
        ),
    ]
