# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-13 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_auto_20171102_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='problemset',
            name='time_limit',
            field=models.TimeField(null=True),
        ),
    ]
