# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-15 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0020_auto_20171114_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedtest',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
