# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-16 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0021_auto_20171115_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedtestproblemobject',
            name='author',
        ),
        migrations.RemoveField(
            model_name='publishedtestproblemobject',
            name='parent_testproblemobject',
        ),
        migrations.RemoveField(
            model_name='publishedtestproblemobject',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='publishedtestproblemobject',
            name='published_test',
        ),
        migrations.RemoveField(
            model_name='publishedtestproblemobject',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='testproblemobject',
            name='author',
        ),
        migrations.RemoveField(
            model_name='testproblemobject',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='testproblemobject',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='testproblemobject',
            name='test',
        ),
        migrations.AddField(
            model_name='problemobject',
            name='a_problemset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.ProblemSet'),
        ),
        migrations.AddField(
            model_name='problemobject',
            name='blank_point_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='problemobject',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Test'),
        ),
        migrations.AddField(
            model_name='publishedproblemobject',
            name='blank_point_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='publishedproblemobject',
            name='problemset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.PublishedProblemSet'),
        ),
        migrations.AddField(
            model_name='publishedproblemobject',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.PublishedTest'),
        ),
        migrations.DeleteModel(
            name='PublishedTestProblemObject',
        ),
        migrations.DeleteModel(
            name='TestProblemObject',
        ),
    ]
