# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-18 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0023_auto_20171116_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedtest',
            name='student_gradeable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='student_gradeable',
            field=models.BooleanField(default=True),
        ),
    ]
