# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-19 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0024_auto_20171117_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='publishedproblemset',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
