# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-25 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0027_auto_20171124_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideobject',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='slideobject',
            name='object_id',
        ),
    ]
