# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-29 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0028_auto_20171124_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedslideobject',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='publishedslideobject',
            name='object_id',
        ),
    ]
