# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-13 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0030_auto_20180313_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedunit',
            name='the_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.PublishedClass'),
        ),
        migrations.AddField(
            model_name='unit',
            name='the_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Class'),
        ),
    ]
