# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-08 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('randomtest', '0100_auto_20180418_0256'),
        ('teacher', '0032_auto_20180410_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedSolutionObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('solution_code', models.TextField(blank=True)),
                ('solution_display', models.TextField(blank=True)),
                ('isSolution', models.BooleanField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('version_number', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_solution_object', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SolutionObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('solution_code', models.TextField(blank=True)),
                ('solution_display', models.TextField(blank=True)),
                ('isSolution', models.BooleanField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('version_number', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution_object', to=settings.AUTH_USER_MODEL)),
                ('problem_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution_objects', to='teacher.ProblemObject')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='randomtest.Solution')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='publishedsolutionobject',
            name='parent_solutionobject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.SolutionObject'),
        ),
        migrations.AddField(
            model_name='publishedsolutionobject',
            name='problem_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution_objects', to='teacher.PublishedProblemObject'),
        ),
        migrations.AddField(
            model_name='publishedsolutionobject',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='randomtest.Solution'),
        ),
    ]
