# Generated by Django 2.2.8 on 2019-12-12 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0033_auto_20180708_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampleproblem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example_problem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problemobject',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_object', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publishedexampleproblem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_example_problem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publishedproblemobject',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_problem_object', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publishedslide',
            name='slidegroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='teacher.PublishedSlideGroup'),
        ),
        migrations.AlterField(
            model_name='publishedslideobject',
            name='slide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slide_objects', to='teacher.PublishedSlide'),
        ),
        migrations.AlterField(
            model_name='publishedsolutionobject',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_solution_object', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publishedunitobject',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_objects', to='teacher.PublishedUnit'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slidegroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='teacher.SlideGroup'),
        ),
        migrations.AlterField(
            model_name='slideobject',
            name='slide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slide_objects', to='teacher.Slide'),
        ),
        migrations.AlterField(
            model_name='solutionobject',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_object', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unitobject',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_objects', to='teacher.Unit'),
        ),
    ]
