# Generated by Django 3.2.23 on 2023-12-18 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0035_auto_20231218_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exampleproblem',
            old_name='slide_object',
            new_name='up_slide_object',
        ),
        migrations.RenameField(
            model_name='imagemodel',
            old_name='slide_object',
            new_name='up_slide_object',
        ),
        migrations.RenameField(
            model_name='proof',
            old_name='slide_object',
            new_name='up_slide_object',
        ),
        migrations.RenameField(
            model_name='theorem',
            old_name='slide_object',
            new_name='up_slide_object',
        ),
    ]
