from django.conf.urls import include#,url
from django.urls import path
from . import views
from .forms import AddProblemForm1,AddProblemForm2MC,AddProblemForm2SA,AddProblemForm2PF,AddProblemForm2MCSA,AddProblemForm3#,UploadContestForm
from .views import AddProblemWizard,show_mc_form_condition,show_sa_form_condition,show_pf_form_condition,show_mcsa_form_condition
from .views import show_mc_form_condition2,show_sa_form_condition2,show_pf_form_condition2,show_mcsa_form_condition2

from django.contrib.auth.decorators import login_required,user_passes_test

addproblem_forms = [AddProblemForm1,
                    AddProblemForm2MC,
                    AddProblemForm2SA,
                    AddProblemForm2PF,
                    AddProblemForm2MCSA,
                    AddProblemForm3,
                    ]

urlpatterns = [
    path('myactivity/', views.my_activity, name='my_activity'),
    path('solutionstats/', views.solution_stats, name='solution_stats'),
    path('solutionstats/<str:username>/', views.solution_stats, name='solution_stats'),
    path('', views.typeview, name='typeview'),
    path('contest/bytag/<str:type>/', views.tagview, name='tagview'),
#    path('^contest/bytag/<str:type>/<str:tag>/', views.typetagview, name='typetagview'),
#    path('^contest/bytag/<str:type>/<str:tag>/<str:label>/', views.problemview, name='problemview'),
    path('contest/bytag/<str:type>/<int:pk>/', views.typetagview, name='typetagview'),
    path('contest/bytag/<str:type>/<int:pk>/<str:label>/', views.problemview, name='problemview'),
    path('contest/bycontest/<str:type>/', views.contests_view, name='contests_view'),
    path('contest/bycontest/<str:type>/matrix/', views.contest_matrixview, name='contest_matrixview'),
    path('contest/bycontest/<str:type>/untagged/', views.untagged_problems_view, name='contest_untagged_problems_view'),
    path('contest/bycontest/<str:type>/<str:short_label>/', views.contesttest_view, name='contest_test_view'),
    path('contest/bycontest/<str:type>/<str:short_label>/pngs/', views.contestproblem_png, name='contestproblem_png_view'),
    path('contest/bycontest/<str:type>/<str:short_label>/sol_pngs/', views.contestproblem_solution_png, name='contestproblem_sols_png_view'),
#    path('contest/bycontest/<str:type>/<str:short_label>/latex/$', views.download_mc_contest_file, name='contest_download_mc_latex_contest'),
    path('contest/bycontest/<str:type>/<str:tag>/<str:label>/', views.problemview, name='contest_problemview'),
    path('contest/bycontest/<str:type>/<str:tag>/<str:label>/png/', views.singleproblem_png, name='contest_singleproblem_png'),
    path('contest/bycontest/<str:type>/<str:tag>/<str:label>/pnga/', views.singleproblem_png_attachment, name='contest_singleproblem_pnga'),
    path('contest/bytest/<str:type>/', views.testview, name='testview'),
    path('contest/bytest/<str:type>/matrix/', views.matrixview, name='matrixview'),
    path('contest/bytest/<str:type>/<str:testlabel>/', views.testlabelview, name='testlabelview'),
    path('contest/bytest/<str:type>/<str:testlabel>/latex/', views.download_mc_contest_file, name='download_mc_latex_contest'),
    path('contest/bytest/<str:type>/<str:testlabel>/sa_latex/', views.download_sa_contest_file, name='download_sa_latex_contest'),
    path('contest/bytest/<str:type>/<str:tag>/<str:label>/', views.problemview, name='problemview'),
    path('contest/bytest/<str:type>/<str:tag>/<str:label>/png/', views.singleproblem_png, name='singleproblem_png'),
    path('contest/bytest/<str:type>/<str:tag>/<str:label>/pnga/', views.singleproblem_png_attachment, name='singleproblem_pnga'),
    path('CM/bytopic/<str:type>/', views.CMtopicview, name='CMtopicview'),
    path('CM/bytopic/<str:type>/<int:pk>/', views.detailedproblemview, name='detailedproblemview'),
    path('CM/bytag/<str:type>/', views.tagview, name='tagview'),
    path('CM/bytag/<str:type>/<str:tag>/', views.CMtypetagview, name='typetagview'),
    path('CM/bytag/<str:type>/<str:tag>/<str:pk>/', views.detailedproblemview, name='detailedproblemview'),
    path('sources/', views.sourceview, name='sourceview'),
    path('sources/book/<int:pk>/', views.bookview, name='bookview'),
    path('sources/book/<int:book_pk>/<int:chapter_pk>/', views.chapterview, name='chapterview'),
    path('sources/book/<int:book_pk>/<int:chapter_pk>/add-sourced-problem/', views.add_sourced_problem, name='add_book_sourced_problem'),
    path('sources/book/<int:book_pk>/<int:chapter_pk>/<int:problem_pk>/', views.problemview, name='chapterproblemview'),
    path('sources/person/<int:person_pk>/', views.personview, name='personview'),
    path('sources/person/<int:person_pk>/add-sourced-problem/', views.add_sourced_problem, name='add_person_sourced_problem'),
    path('sources/person/<int:person_pk>/<int:problem_pk>/', views.problemview, name='personproblemview'),
    path('sources/contest/<int:contest_pk>/', views.contestview, name='contestview'),
    path('sources/contest/<int:contest_pk>/add-sourced-problem/', views.add_sourced_problem, name='add_contest_sourced_problem'),
    path('sources/contest/<int:contest_pk>/<int:problem_pk>/', views.problemview, name='contestproblemview'),
    path('addproblemform/',AddProblemWizard.as_view(addproblem_forms,condition_dict={'1':show_mc_form_condition,'2':show_sa_form_condition,'3':show_pf_form_condition,'4':show_mcsa_form_condition,})),
    path('addcontest/<str:type>/<int:num>/',views.addcontestview, name='addcontestview'),
    path('uploadcontest/<str:type2>/htmltolatex/',views.htmltolatex, name='htmltolatex'),
    path('uploadcontest/<str:type>/',views.uploadcontestview, name='uploadcontestview'),
    path('uploadcontest/<str:type>/preview/',views.uploadpreview, name='uploadpreview'),

#    path('tameuploadcontest/',views.tameupload, name='tameupload'),
#    path('tameuploadcontest/preview/',views.uploadpreview, name='uploadpreview'),
    path('duplicateview/<str:type_name>/',views.duplicate_view, name='duplicate_view'),
    path('redirectproblem/<int:pk>/',views.redirectproblem, name='redirect_problem_view'),################FIX THIS FOR SOURCES
    path('redirectcontest/<int:pk>/',views.redirectcontest, name='redirect_contest_view'),
    path('tags/',views.tageditview,name='tageditview'),

    path('tags/edit_tag/<int:pk>/', login_required(views.TagUpdateView.as_view()),name="update_tag"),
    path('tags/add_tag/<int:pk>/', login_required(views.TagCreateView.as_view()),name="add_new_tag"),
    path('tags/delete_tag/<int:pk>/', user_passes_test(lambda u: u.is_superuser)(views.TagDeleteView.as_view()),name="delete_tag"),
    path('tags/info_tag/<int:pk>/', views.taginfoview,name="info_tag"),
    path('tags/<int:pk>/', views.TagProblemList.as_view(),name="tag_problem_view"),
    path('edittypes/', views.edittypes,name='edit_types'),
    path('asy/', views.asymptotr,name='asymptotr'),
    path('asy/pdf/', views.asymptotr_pdf,name='asymptotr_pdf'),
    path('relays/', views.relay_index,name='relay_index'),
    path('relays/addrelayform/', views.add_relay_form,name='add_relay_form'),
    path('relays/<str:label>/', views.relay_view,name='relay_view'),
    path('relays/<str:label>/pdf/', views.relay_pdf_view,name='relay_pdf_view'),
    path('relays/<str:label>/zip/', views.relay_problem_zip,name='relay_problem_zip'),
###########
    path('ajax/remove_duplicate/', views.remove_duplicate_problem, name='remove_duplicate'),
    path('ajax/add_duplicate/', views.add_duplicate_problem, name='add_duplicate'),
    path('ajax/load-edit-answer/', views.load_edit_answer, name='load_edit_answer'),
    path('ajax/load-edit-latex/', views.load_edit_latex, name='load_edit_latex'),
    path('ajax/view-mc-latex/', views.view_mc_latex, name='view_mc_latex'),
    path('ajax/save-latex/', views.save_latex, name='save_latex'),
    path('ajax/save-answer/', views.save_answer, name='save_answer'),
    path('ajax/load_sol/<int:pk>/', login_required(views.SolutionView.as_view()), name='load_solution'),
    path('ajax/load-edit-sol/', views.load_edit_sol, name='load_edit_solution'),
    path('ajax/save-sol/', views.save_sol, name='save_solution'),
    path('ajax/load-new-solution/', views.load_new_solution, name='load_new_solution'),
    path('ajax/save-new-solution/', views.save_new_solution, name='save_new_solution'),
    path('ajax/delete-solution/', views.delete_sol, name='delete_sol'),
    path('ajax/add_tag/', views.add_tag, name='add_tag'),
    path('ajax/delete_tag/', views.delete_tag, name='delete_tag'),
    path('ajax/change-qt/', views.change_qt, name='change_qt'),
    path('ajax/change-qt-load/', views.change_qt_load, name='change_qt_load'),
    path('ajax/save-qt/', views.save_qt, name='save_qt'),
    path('ajax/load-change-difficulty/', views.load_change_difficulty, name='load_change_difficulty'),
    path('ajax/save-difficulty/', views.save_difficulty, name='save_difficulty'),
    path('ajax/load-edit-review/', views.load_edit_review, name='load_edit_review'),
    path('ajax/new-review/', views.new_review, name='new_review'),
    path('ajax/save-new-review/', views.save_new_review, name='save_new_review'),
    path('ajax/save-review/', views.save_review, name='save_review'),
    path('ajax/new-comment/', views.new_comment, name='new_comment'),
    path('ajax/save-comment/', views.save_comment, name='save_comment'),
    path('ajax/delete-comment/', views.delete_comment, name='delete_comment'),
    path('ajax/new-new-comment/', views.new_new_comment, name='new_new_comment'),
    path('ajax/save-new-comment/', views.save_new_comment, name='save_new_comment'),
    path('ajax/delete-new-comment/', views.delete_new_comment, name='delete_new_comment'),
    path('ajax/change-needs-answers/', views.change_needs_answers, name='change_needs_answers'),
    path('ajax/load-new-type/', views.load_new_type, name='load_new_type'),
    path('ajax/save-type/', views.save_type, name='save_type'),
    path('ajax/load-edit-type/', views.load_edit_type, name='load_edit_type'),
    path('ajax/save-edit-type/', views.save_edit_type, name='save_edit_type'),
    path('ajax/load-new-round/', views.load_new_round, name='load_new_round'),
    path('ajax/save-round/', views.save_round, name='save_round'),
    path('ajax/load-new-book/', views.load_new_book, name='load_new_book'),
    path('ajax/load-new-contest/', views.load_new_contest, name='load_new_contest'),
    path('ajax/load-new-person/', views.load_new_person, name='load_new_person'),
    path('ajax/save-source/', views.save_source, name='save_source'),
    path('ajax/load-new-chapter/', views.load_new_chapter, name='load_new_chapter'),
    path('ajax/save-chapter/', views.save_chapter, name='save_chapter'),
    path('ajax/load-add-sourced-problem/', views.load_addproblemform, name='load_add_sourced_problem'),
    path('ajax/load-sourced-problem/', views.load_qt_addproblemform, name='load_qt_sourced_problem'),
    path('ajax/view_log/', views.view_entry_log, name='view_log'),
    path('ajax/refresh-matrix-row/', views.refresh_matrix_row, name='refresh_matrix_row'),
    path('ajax/new-accepted-answer/', views.load_new_accepted_answer, name='load_new_accepted_answer'),
    path('ajax/add-accepted-answer/', views.add_accepted_answer, name='add_accepted_answer'),
    path('ajax/load-edit-accepted-answer/', views.load_edit_accepted_answer, name='load_edit_accepted_answer'),
    path('ajax/save-accepted-answer/', views.save_accepted_answer, name='save_accepted_answer'),
    path('ajax/delete-accepted-answer/', views.delete_accepted_answer, name='delete_accepted_answer'),
    path('ajax/load-edit-relay-answer/', views.load_edit_relay_answer, name='load_edit_relay_answer'),
    path('ajax/save-relay-answer/', views.save_relay_answer, name='save_relay_answer'),
    path('ajax/load-edit-relay-backward-answer/', views.load_edit_relay_backward_answer, name='load_edit_relay_backward_answer'),
    path('ajax/save-relay-backward-answer/', views.save_backward_relay_answer, name='save_backward_relay_answer'),
    path('ajax/load-edit-relay-latex/', views.load_edit_relay_latex, name='load_edit_relay_latex'),
    path('ajax/save-relay-latex/', views.save_relay_latex, name='save_relay_latex'),
#    path('tameuploadcontest/preview/',views.ContestUploadPreview(UploadContestForm), name='uploadpreview'),
#    path('bytag/(?P<type>\w+)/untagged/', views.untaggedview, name='untaggedview'),
#    path('bytest/(?P<type>\w+)/untagged/', views.untaggedview, name='untaggedview'),
#    path('untagged/(?P<type>\w+)/', views.untaggedview, name='untaggedview'),
]
