# Generated by Django 3.2.23 on 2025-03-10 02:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('number', models.IntegerField()),
                ('readable_label', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DrillProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('label', models.CharField(max_length=255)),
                ('readable_label', models.CharField(max_length=255)),
                ('problem_text', models.TextField()),
                ('display_problem_text', models.TextField()),
                ('topic', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('percent_solved', models.FloatField()),
                ('number_solved', models.IntegerField()),
                ('is_bonus', models.BooleanField(default=False)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drills.drill')),
            ],
        ),
        migrations.CreateModel(
            name='DrillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DrillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drills.drill')),
                ('drill_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drills.drillprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DrillTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('topic', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrillRecordProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Correct'), (0, 'Incorrect')])),
                ('silly_mistake', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('drill_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drills.drillproblem')),
                ('drillrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drills.drillrecord')),
            ],
        ),
        migrations.CreateModel(
            name='DrillProblemSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('solution_text', models.TextField()),
                ('display_solution_text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('drill_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drills.drillproblem')),
            ],
        ),
        migrations.AddField(
            model_name='drillproblem',
            name='drill_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drills.drilltask'),
        ),
        migrations.CreateModel(
            name='DrillAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('problem_tasks', models.ManyToManyField(to='drills.DrillTask')),
            ],
        ),
    ]
