# Generated by Django 3.2.23 on 2025-03-10 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='drill',
            name='average_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drill',
            name='num_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drillproblem',
            name='drill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_problems', to='drills.drill'),
        ),
        migrations.AlterField(
            model_name='drillrecord',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='drillrecordproblem',
            name='status',
            field=models.IntegerField(choices=[(1, 'Correct'), (0, 'Incorrect'), (-1, 'Blank')]),
        ),
        migrations.AddField(
            model_name='drillprofile',
            name='year',
            field=models.ManyToManyField(related_name='profiles', to='drills.YearFolder'),
        ),
    ]
