# Generated by Django 3.2.23 on 2025-03-10 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0002_auto_20250310_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drillprofile',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='drillrecord',
            name='drill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_records', to='drills.drill'),
        ),
        migrations.AlterField(
            model_name='drillrecordproblem',
            name='drillrecord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_record_problems', to='drills.drillrecord'),
        ),
    ]
