# Generated by Django 3.2.23 on 2025-03-12 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0003_auto_20250310_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drill',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='drillassignment',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='drillproblem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='drillproblemsolution',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='drillrecord',
            options={'ordering': ['-score']},
        ),
        migrations.AlterModelOptions(
            name='drillrecordproblem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='yearfolder',
            options={'ordering': ['year']},
        ),
        migrations.AddField(
            model_name='drill',
            name='year_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drills', to='drills.yearfolder'),
        ),
        migrations.AddField(
            model_name='drillassignment',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='drillassignment',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='drills.yearfolder'),
        ),
        migrations.AddField(
            model_name='yearfolder',
            name='top_number',
            field=models.IntegerField(default=0),
        ),
    ]
