# Generated by Django 3.2.23 on 2025-07-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0005_auto_20250706_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
