# Generated by Django 3.2.23 on 2025-07-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0006_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillrecord',
            name='bonus_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drillrecord',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
