# Generated by Django 3.2.23 on 2025-08-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0007_auto_20250709_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearfolder',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
