# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('num_problems', models.IntegerField()),
                ('num_problems_correct', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_attempted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('problems', models.ManyToManyField(to='randomtest.Problem')),
                ('types', models.ManyToManyField(to='randomtest.Type')),
            ],
        ),
    ]
