# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0003_tests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tests',
            field=models.ManyToManyField(to='randomtest.Test'),
        ),
    ]
