# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0004_auto_20161016_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='num_problems',
        ),
    ]
