# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0006_auto_20161017_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='question_type',
            field=models.ManyToManyField(to='randomtest.QuestionType'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solutions',
            field=models.ManyToManyField(to='randomtest.Solution'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(to='randomtest.Tag'),
        ),
    ]
