# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0009_auto_20161018_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=10)),
                ('problem_label', models.CharField(max_length=20)),
                ('parent_test_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='answers',
            field=models.ManyToManyField(blank=True, to='randomtest.Answer'),
        ),
    ]
