# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0010_auto_20161018_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='form',
            new_name='form_letter',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='testlabel',
            new_name='test_label',
        ),
    ]
