# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0011_auto_20161018_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(related_name='problems', to='randomtest.Tag'),
        ),
    ]
