# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0012_auto_20161022_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='parent_test_name',
        ),
        migrations.AlterField(
            model_name='test',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='parent_test', to='randomtest.Answer'),
        ),
    ]
