# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0014_auto_20161025_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='label',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
