# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0015_type_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, max_length=10)),
                ('problem_label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_problems_correct', models.IntegerField()),
                ('responses', models.ManyToManyField(blank=True, to='randomtest.Response')),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='test',
            name='num_problems_correct',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='responses',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomtest.Test'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allresponses',
            field=models.ManyToManyField(blank=True, to='randomtest.Responses'),
        ),
    ]
