# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0016_auto_20161027_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='num_problems_correct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allresponses',
            field=models.ManyToManyField(blank=True, related_name='user_profile', to='randomtest.Responses'),
        ),
    ]
