# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0017_auto_20161027_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='readable_label',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
