# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0018_problem_readable_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer_choices',
            field=models.TextField(blank=True),
        ),
    ]
