# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0019_problem_answer_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='types',
            field=models.ManyToManyField(blank=True, to='randomtest.Type'),
        ),
    ]
