# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 22:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('randomtest', '0020_auto_20161102_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='authors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
