# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0021_solution_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='show_answer_marks',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='show_answer_marks',
            field=models.BooleanField(default=0),
        ),
    ]
