# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0024_auto_20161127_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='year',
            field=models.IntegerField(default=2016),
        ),
    ]
