# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0025_auto_20161127_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='problem',
            name='author_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_number',
            field=models.IntegerField(default=0),
        ),
    ]
