# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0026_auto_20161128_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_number',
            field=models.IntegerField(default=1),
        ),
    ]
