# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0028_auto_20161128_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='top_index',
            field=models.IntegerField(default=0),
        ),
    ]
