# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0029_type_top_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer_A',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='problem',
            name='answer_B',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='problem',
            name='answer_C',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='problem',
            name='answer_D',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='problem',
            name='answer_E',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='problem',
            name='mc_answer',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='problem',
            name='mc_problem_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='question_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_type_new', to='randomtest.QuestionType'),
        ),
        migrations.AddField(
            model_name='problem',
            name='sa_answer',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_new', to='randomtest.Type'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='problems', to='randomtest.Tag'),
        ),
    ]
