# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0032_problemapproval_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
