# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0033_auto_20170118_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='attempted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='responses',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
