# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0034_auto_20170125_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_label', models.CharField(blank=True, max_length=50)),
                ('response', models.CharField(blank=True, max_length=10)),
                ('problem_label', models.CharField(max_length=30)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('correct', models.BooleanField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='responselog',
            field=models.ManyToManyField(blank=True, to='randomtest.UserResponse'),
        ),
    ]
