# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0035_auto_20170125_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='test_pk',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
