# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0036_userresponse_test_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='top_solution_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
