# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0038_userprofile_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='stickied',
            field=models.BooleanField(default=0),
        ),
    ]
