# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0039_response_stickied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticky',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_label', models.CharField(max_length=20)),
                ('sticky_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('test_pk', models.CharField(max_length=15)),
                ('test_label', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stickies',
            field=models.ManyToManyField(blank=True, to='randomtest.Sticky'),
        ),
    ]
