# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0041_testcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTimeStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('test_pk', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='archived_tests',
            field=models.ManyToManyField(blank=True, related_name='archived_tests', to='randomtest.Test'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timestamps',
            field=models.ManyToManyField(blank=True, to='randomtest.TestTimeStamp'),
        ),
    ]
