# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0042_auto_20170209_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tests', models.ManyToManyField(to='randomtest.Test')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='folders', to='randomtest.Folder'),
        ),
    ]
