# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0043_auto_20170224_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='point_value',
            field=models.IntegerField(default=0),
        ),
    ]
