# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0044_userresponse_point_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_probs', models.IntegerField()),
                ('num_correct', models.IntegerField(default=0)),
                ('responses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertestresponses', to='randomtest.Responses')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomtest.Test')),
            ],
        ),
    ]
