# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0045_usertest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usertests',
            field=models.ManyToManyField(blank=True, to='randomtest.UserTest'),
        ),
    ]
