# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0046_userprofile_usertests'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_attempted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_problems', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SortableProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newtest_pk', models.CharField(max_length=15)),
                ('order', models.IntegerField(default=0)),
                ('problem_pk', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='type',
            name='default_question_type',
            field=models.CharField(default='pf', max_length=4),
        ),
        migrations.AddField(
            model_name='type',
            name='form_space',
            field=models.CharField(default=' ', max_length=1),
        ),
        migrations.AddField(
            model_name='newtest',
            name='problems',
            field=models.ManyToManyField(to='randomtest.SortableProblem'),
        ),
        migrations.AddField(
            model_name='newtest',
            name='types',
            field=models.ManyToManyField(blank=True, to='randomtest.Type'),
        ),
    ]
