# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0047_auto_20170404_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(default='manager', max_length=15),
        ),
    ]
