# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-23 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0048_userprofile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='form_space',
        ),
        migrations.AddField(
            model_name='type',
            name='readable_label_post_form',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='type',
            name='readable_label_pre_form',
            field=models.CharField(default='', max_length=20),
        ),
    ]
