# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-22 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0049_auto_20170523_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(default='member', max_length=15),
        ),
    ]
