# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-22 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0050_auto_20170622_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='duplicate_problems',
            field=models.ManyToManyField(blank=True, related_name='_problem_duplicate_problems_+', to='randomtest.Problem'),
        ),
    ]
