# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-28 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0051_problem_duplicate_problems'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('problems', models.ManyToManyField(to='randomtest.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='problem_groups',
            field=models.ManyToManyField(blank=True, related_name='problem_groups', to='randomtest.ProblemGroup'),
        ),
    ]
