# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-03 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0052_auto_20170628_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemgroup',
            name='is_shared',
            field=models.BooleanField(default=0),
        ),
    ]
