# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-14 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0053_problemgroup_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='solution',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
