# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-15 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('randomtest', '0054_auto_20170814_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='is_contest',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activity_log',
            field=models.ManyToManyField(blank=True, related_name='activity_log', to='admin.LogEntry'),
        ),
    ]
