# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-17 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0055_auto_20170815_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='activity_log',
        ),
    ]
