# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-19 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0056_remove_userprofile_activity_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtest',
            name='last_attempted_date',
        ),
        migrations.RemoveField(
            model_name='sortableproblem',
            name='problem_pk',
        ),
        migrations.AddField(
            model_name='sortableproblem',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='randomtest.Problem'),
        ),
        migrations.AlterField(
            model_name='newtest',
            name='problems',
            field=models.ManyToManyField(blank=True, to='randomtest.SortableProblem'),
        ),
        migrations.AlterField(
            model_name='newtest',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='types', to='randomtest.Type'),
        ),
    ]
