# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-19 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0058_auto_20170819_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='display_solution_text',
            field=models.TextField(blank=True),
        ),
    ]
