# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-19 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0060_response_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='latex_label',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
