# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-26 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0005_auto_20170826_1324'),
        ('randomtest', '0061_problem_latex_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='handouts',
            field=models.ManyToManyField(blank=True, related_name='handouts', to='handouts.Handout'),
        ),
    ]
