# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-04 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0063_auto_20170829_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='newtests',
            field=models.ManyToManyField(blank=True, related_name='newtests', to='randomtest.NewTest'),
        ),
    ]
