# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-05 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0064_userprofile_newtests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sortableproblem',
            options={'ordering': ['order']},
        ),
    ]
