# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-08 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0065_auto_20170904_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_number_prefix',
            field=models.CharField(default='', max_length=5),
        ),
    ]
