# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-13 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0066_problem_problem_number_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=0)),
                ('children', models.ManyToManyField(blank=True, related_name='_newtag_children_+', to='randomtest.NewTag')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='randomtest.NewTag')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='newtags',
            field=models.ManyToManyField(blank=True, related_name='problems', to='randomtest.NewTag'),
        ),
    ]
