# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-13 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0067_auto_20170912_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtag',
            name='children',
        ),
        migrations.AlterField(
            model_name='newtag',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='randomtest.NewTag'),
        ),
    ]
