# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-14 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0068_auto_20170912_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newtag',
            options={'ordering': ['label']},
        ),
        migrations.AlterField(
            model_name='problem',
            name='type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='randomtest.Type'),
        ),
    ]
