# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-18 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0069_auto_20170914_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, max_length=10)),
                ('problem_label', models.CharField(max_length=20)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempted', models.BooleanField(default=0)),
                ('stickied', models.BooleanField(default=0)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='randomtest.Problem')),
            ],
        ),
        migrations.AlterModelOptions(
            name='newtag',
            options={'ordering': ['tag']},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['label']},
        ),
        migrations.AddField(
            model_name='usertest',
            name='userprof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tests', to='randomtest.UserProfile'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='responses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertest', to='randomtest.Responses'),
        ),
        migrations.AddField(
            model_name='newresponse',
            name='usertest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newresponses', to='randomtest.UserTest'),
        ),
    ]
