# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-18 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0070_auto_20170918_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='show_answer_marks',
            field=models.BooleanField(default=0),
        ),
    ]
