# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-20 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0072_auto_20170918_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='newresponse',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertest',
            name='newtest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='randomtest.NewTest'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='randomtest.Test'),
        ),
    ]
