# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-20 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0073_auto_20170920_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='newresponse',
            name='point_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='newresponse',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sortableproblem',
            name='newtest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='randomtest.NewTest'),
        ),
        migrations.AlterField(
            model_name='newtest',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='new_test', to='randomtest.SortableProblem'),
        ),
        migrations.AlterField(
            model_name='newtest',
            name='types',
            field=models.ManyToManyField(blank=True, to='randomtest.Type'),
        ),
    ]
