# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-26 00:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0075_remove_userprofile_handouts'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='my_TA_classes',
            field=models.ManyToManyField(related_name='TA_userprofiles', to='teacher.PublishedClass'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='my_classes',
            field=models.ManyToManyField(related_name='userprofiles', to='teacher.Class'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='my_published_classes',
            field=models.ManyToManyField(related_name='userprofiles', to='teacher.PublishedClass'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allresponses',
            field=models.ManyToManyField(blank=True, related_name='userprofiles', to='randomtest.Responses'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='archived_tests',
            field=models.ManyToManyField(blank=True, related_name='userprofiles', to='randomtest.Test'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='userprofiles', to='randomtest.Folder'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='newtests',
            field=models.ManyToManyField(blank=True, related_name='userprofiles', to='randomtest.NewTest'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='problem_groups',
            field=models.ManyToManyField(blank=True, related_name='userprofiles', to='randomtest.ProblemGroup'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='userprofiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
