# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-21 01:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('randomtest', '0078_userprofile_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtag',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='teacher_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
