# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-16 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0080_solution_parent_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
