# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-01 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0081_problem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='editable_problem_groups',
            field=models.ManyToManyField(blank=True, related_name='editoruserprofiles', to='randomtest.ProblemGroup'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='readonly_problem_groups',
            field=models.ManyToManyField(blank=True, related_name='readeruserprofiles', to='randomtest.ProblemGroup'),
        ),
    ]
