# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-03 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0083_collaboratorrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemGroupObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=4)),
                ('is_owner', models.BooleanField(default=0)),
                ('problem_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_group_objects', to='randomtest.ProblemGroup')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_group_objects', to='randomtest.UserProfile')),
            ],
        ),
    ]
