# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-03 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0084_problemgroupobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemgroupobject',
            name='problem_group',
        ),
        migrations.RemoveField(
            model_name='problemgroupobject',
            name='userprofile',
        ),
        migrations.DeleteModel(
            name='ProblemGroupObject',
        ),
    ]
