# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-03 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0085_auto_20180203_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='owned_problem_groups',
            field=models.ManyToManyField(blank=True, related_name='owneruserprofiles', to='randomtest.ProblemGroup'),
        ),
    ]
