# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-06 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0086_userprofile_owned_problem_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticky',
            name='usertest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='randomtest.UserTest'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='usertest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='randomtest.UserTest'),
        ),
    ]
