# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-06 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0087_auto_20180205_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticky',
            name='test_pk',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='timestamps',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='test_pk',
        ),
        migrations.DeleteModel(
            name='TestTimeStamp',
        ),
    ]
