# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-06 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0088_auto_20180206_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='needs_answers',
            field=models.BooleanField(default=0),
        ),
    ]
