# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-11 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0089_problem_needs_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='sa_answer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
