# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-14 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0090_auto_20180210_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('default_question_type', models.CharField(default='pf', max_length=4)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='randomtest.Type')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='problem',
            name='sa_answer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='problem',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='randomtest.Round'),
        ),
    ]
