# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-14 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0091_auto_20180213_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='readable_label_post_form',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='round',
            name='readable_label_pre_form',
            field=models.CharField(default='', max_length=20),
        ),
    ]
