# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-14 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0092_auto_20180213_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='test_label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
