# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-24 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0093_auto_20180214_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='readable_label_post_form',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='round',
            name='readable_label_pre_form',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='readable_label_post_form',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='readable_label_pre_form',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
