# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-05 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0029_auto_20171129_0124'),
        ('randomtest', '0095_type_allow_form_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='editable_my_classes',
            field=models.ManyToManyField(related_name='editoruserprofiles', to='teacher.Class'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='owned_my_classes',
            field=models.ManyToManyField(related_name='owneruserprofiles', to='teacher.Class'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='readonly_my_classes',
            field=models.ManyToManyField(related_name='readonlyuserprofiles', to='teacher.Class'),
        ),
    ]
