# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-05 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0096_auto_20180305_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='readonly_my_classes',
            field=models.ManyToManyField(related_name='readeruserprofiles', to='teacher.Class'),
        ),
    ]
