# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-17 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0098_auto_20180416_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('chapter_number', models.IntegerField()),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='randomtest.Source')),
            ],
            options={
                'ordering': ['chapter_number'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='book_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='randomtest.BookChapter'),
        ),
    ]
