# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-18 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0099_auto_20180416_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
