# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-11 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0102_problemgroupobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='contest_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='randomtest.ContestTest'),
        ),
    ]
