# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-11 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0104_auto_20190311_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contesttest',
            options={'ordering': ['year', 'form_letter', 'contest_label']},
        ),
    ]
