# Generated by Django 2.2.12 on 2020-05-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0107_auto_20191212_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedSearchPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('rounds', models.ManyToManyField(blank=True, to='randomtest.Round')),
                ('types', models.ManyToManyField(blank=True, to='randomtest.Type')),
            ],
        ),
    ]
