# Generated by Django 2.2.12 on 2020-08-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0108_advancedsearchpreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='newresponse',
            name='correct',
            field=models.BooleanField(default=0),
        ),
    ]
