# Generated by Django 2.2.12 on 2020-08-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0109_newresponse_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='archived_editable_problem_groups',
            field=models.ManyToManyField(blank=True, related_name='a_editoruserprofiles', to='randomtest.ProblemGroup'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='archived_owned_problem_groups',
            field=models.ManyToManyField(blank=True, related_name='a_owneruserprofiles', to='randomtest.ProblemGroup'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='archived_problem_groups',
            field=models.ManyToManyField(blank=True, related_name='a_userprofiles', to='randomtest.ProblemGroup'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='archived_readonly_problem_groups',
            field=models.ManyToManyField(blank=True, related_name='a_readeruserprofiles', to='randomtest.ProblemGroup'),
        ),
    ]
