# Generated by Django 2.2.12 on 2021-03-06 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0110_auto_20200805_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(choices=[('INT', 'Integer'), ('CF', 'Common Fraction'), ('DEC', 'Decimal'), ('MIX', 'Mixed Number'), ('DOL', 'Dollars'), ('WKD', 'Day of the Week'), ('SQR', 'Square Root'), ('RAD', 'Radical (a*sqrt(b))'), ('CFQ', 'Common Fraction in Simplest Radical Form (a*sqrt(b)/c)'), ('OPR', 'Ordered Pair'), ('TEX', 'Text'), ('PCT', 'Percent')], default='INT', max_length=3)),
                ('answer_a', models.CharField(default='', max_length=50)),
                ('answer_b', models.CharField(default='', max_length=50)),
                ('answer_c', models.CharField(default='', max_length=50)),
                ('units', models.CharField(default='', max_length=50)),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_answers', to='randomtest.Problem')),
            ],
        ),
    ]
