# Generated by Django 2.2.12 on 2022-01-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0115_auto_20210310_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemgroup',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
