# Generated by Django 2.2.12 on 2023-06-11 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0118_newcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcomment',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
