# Generated by Django 3.2.23 on 2024-04-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0121_relayproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='relayproblem',
            name='contest',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
