# Generated by Django 5.2.17 on 2026-08-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0122_relayproblem_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='duplicate_problems',
            field=models.ManyToManyField(blank=True, to='randomtest.problem'),
        ),
    ]
