from django.conf.urls import include#,url
from django.urls import path
from . import views
#from views import TestDelete

urlpatterns = [
    path('', views.tableview, name='g_tableview'),
    path('archived/', views.archivedtableview, name='g_archived_tableview'),
    path('tags/', views.tagtableview, name='tagtableview'),
    path('tags/<int:pk>/', views.viewtaggroup, name='viewtaggroup'),
    path('<int:pk>/', views.viewproblemgroup, name='viewproblemgroup'),
    path('<int:pk>/edit/', views.edit_pg_view, name='editproblemgroup'),
    path('<int:pk>/intersection/<int:target_pk>/', views.viewproblemgroup_intersection, name='viewproblemgroup_intersection'),
    path('<int:pk>/without/<int:target_pk>/', views.viewproblemgroup_without, name='viewproblemgroup_without'),
    path('ajax/savegroup/', views.savegroup, name='savegroup'),
    path('ajax/create-test/', views.create_test, name='g_createtest'),
    path('ajax/edit-sharing/', views.load_sharing_modal, name='edit_sharing'),
    path('ajax/share-with-user/', views.share_with_user, name='share_with_user'),
    path('ajax/change-permission/', views.change_permission, name='change_permission'),
    path('ajax/delete-group/', views.delete_group, name='delete_group'),
    path('ajax/remove-group/', views.remove_group, name='remove_group'),
    path('ajax/archive-group/', views.archive_group, name='archive_group'),
    path('ajax/unarchive-group/', views.unarchive_group, name='unarchive_group'),
    path('ajax/add-to-group/', views.add_to_group, name='groups_add_to_group'),
    path('ajax/fetch-problems/', views.fetch_problems, name='groups_fetch_problems'),
    path('ajax/new-problemgroup/', views.newproblemgroup, name='groups_new_pg'),
    path('ajax/edit-prob_group-name/',views.editprobgroupname, name="editprobgroupname"),
    path('ajax/edit-prob_group-description/',views.editprobgroupdescription, name="editprobgroupdescription"),
    path('ajax/save-prob_group-name/',views.saveprobgroupname, name="saveprobgroupname"),
    path('ajax/save-prob_group-description/',views.saveprobgroupdescription, name="saveprobgroupdescription"),
    path('<int:pk>/pdf/', views.test_as_pdf, name='pgpdfview'),
    path('<int:pk>/outlinepdf/', views.outline_test_as_pdf, name='pgoutlinepdfview'),
    path('<int:pk>/outlinetex/', views.outline_test_as_tex, name='pgoutlinetexview'),
    path('<int:pk>/twoatatimepdf/', views.twoatatime_test_as_pdf, name='pgtwoatatimepdfview'),
    path('<int:pk>/drillpdf/', views.drill_test_as_pdf, name='pgdrillpdfview'),
    path('<int:pk>/latex/', views.latex_view, name='pglatexview'),
    path('<int:pk>/answerkey/', views.group_answer_key_as_pdf, name='pganswerkeyview'),
    path('<int:pk>/search/', views.searchform, name='pgsearchform'),
    path('<int:pk>/search/results/', views.searchresults, name='searchresults'),
    path('<int:pk>/search/advanced_results/', views.advanced_searchresults, name='advancedsearchresults'),
    path('<int:pk>/search/results/add_to_group/', views.search_add_to_group, name='add_to_group'),
    path('<int:pk>/search/results/add-all-problems/',views.addallproblems, name="addallproblems"),
    path('<int:pk>/search/advanced_results/add_to_group/', views.search_add_to_group, name='add_to_group'),
    path('<int:pk>/search/results/add_to_this_group/', views.add_to_this_group, name='add_to_this_group'),
    path('<int:pk>/search/advanced_results/add-all-problems/',views.advanced_addallproblems, name="advanced_addallproblems"),
    path('<int:pk>/search/advanced_results/add_to_this_group/', views.add_to_this_group, name='add_to_this_group'),
    path('ajax/load_sol/<int:pk>/', views.load_sols, name='search_load_solution'),

]
