# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-12 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclass',
            name='num_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userclass',
            name='num_problems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userproblemset',
            name='num_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userproblemset',
            name='num_problems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userunit',
            name='num_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userunit',
            name='num_problems',
            field=models.IntegerField(default=0),
        ),
    ]
