# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-14 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_auto_20171011_2319'),
        ('student', '0002_auto_20171011_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSlides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('slides', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.SlideGroup')),
                ('user_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.UserUnit')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='userproblemset',
            name='is_initialized',
            field=models.BooleanField(default=0),
        ),
    ]
