# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-14 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20171014_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question_type',
        ),
    ]
