# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-15 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_response_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticky',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticky_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('problemset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.UserProblemSet')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Response')),
            ],
        ),
    ]
