# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-15 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('randomtest', '0076_auto_20170925_1952'),
        ('student', '0005_sticky'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_response', models.CharField(blank=True, max_length=10)),
                ('problem_label', models.CharField(max_length=30)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('correct', models.BooleanField(default=0)),
                ('point_value', models.IntegerField(default=0)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Response')),
                ('user_problemset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.UserProblemSet')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_responselog', to='randomtest.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='sticky',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_stickies', to='randomtest.UserProfile'),
        ),
    ]
