# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-15 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20171014_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='problem_label',
            new_name='readable_label',
        ),
    ]
