# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-15 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20171014_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticky',
            name='readable_label',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
