# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-21 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('student', '0008_sticky_readable_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUnitObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.UserUnit')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
