# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-21 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_userunitobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userunitobject',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userunitobject',
            name='object_id',
        ),
    ]
