# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-21 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20171020_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproblemset',
            name='user_unit',
        ),
        migrations.RemoveField(
            model_name='userslides',
            name='user_unit',
        ),
    ]
