# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-21 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20171020_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslides',
            name='num_slides',
            field=models.IntegerField(default=0),
        ),
    ]
