# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-21 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_userslides_num_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='userunit',
            name='num_problemsets',
            field=models.IntegerField(default=0),
        ),
    ]
