# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-03 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_auto_20171102_1855'),
        ('student', '0014_userunit_num_problemsets'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='publishedproblem_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.PublishedProblemObject'),
        ),
        migrations.AddField(
            model_name='userproblemset',
            name='published_problemset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.PublishedProblemSet'),
        ),
        migrations.AddField(
            model_name='userslides',
            name='published_slides',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.PublishedSlideGroup'),
        ),
        migrations.AddField(
            model_name='userunit',
            name='published_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.PublishedUnit'),
        ),
    ]
