# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-04 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20171102_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='problem_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.ProblemObject'),
        ),
        migrations.AlterField(
            model_name='userproblemset',
            name='problemset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.ProblemSet'),
        ),
        migrations.AlterField(
            model_name='userslides',
            name='slides',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.SlideGroup'),
        ),
        migrations.AlterField(
            model_name='userunit',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Unit'),
        ),
    ]
