# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-14 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20171103_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproblemset',
            name='in_progress',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userproblemset',
            name='is_graded',
            field=models.BooleanField(default=0),
        ),
    ]
