# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-14 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20171114_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproblemset',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
