# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-16 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0021_auto_20171115_1340'),
        ('student', '0018_userproblemset_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField()),
                ('points_earned', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('num_problems', models.IntegerField(default=0)),
                ('num_correct', models.IntegerField(default=0)),
                ('is_initialized', models.BooleanField(default=0)),
                ('in_progress', models.BooleanField(default=0)),
                ('is_graded', models.BooleanField(default=0)),
                ('start_time', models.DateTimeField(null=True)),
                ('published_test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.PublishedTest')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Test')),
                ('userunitobject', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.UserUnitObject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
