# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-18 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20171116_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticky',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.UserTest'),
        ),
        migrations.AlterField(
            model_name='sticky',
            name='problemset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.UserProblemSet'),
        ),
    ]
