# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-18 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20171117_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='points_earned',
            field=models.FloatField(),
        ),
    ]
