# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-15 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20171117_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='num_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
