# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-11 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0032_auto_20180410_2256'),
        ('student', '0023_response_num_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userunitobject',
            name='unit_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.PublishedUnitObject'),
        ),
    ]
