# Generated by Django 2.2.8 on 2019-12-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_auto_20180410_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='problem_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.ProblemObject'),
        ),
        migrations.AlterField(
            model_name='response',
            name='publishedproblem_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.PublishedProblemObject'),
        ),
        migrations.AlterField(
            model_name='sticky',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Response'),
        ),
        migrations.AlterField(
            model_name='userclass',
            name='published_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.PublishedClass'),
        ),
        migrations.AlterField(
            model_name='userclass',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userclasses', to='randomtest.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userproblemset',
            name='problemset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.ProblemSet'),
        ),
        migrations.AlterField(
            model_name='userproblemset',
            name='published_problemset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.PublishedProblemSet'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Response'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='user_problemset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.UserProblemSet'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_responselog', to='randomtest.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userslides',
            name='published_slides',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.PublishedSlideGroup'),
        ),
        migrations.AlterField(
            model_name='userslides',
            name='slides',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.SlideGroup'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='published_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.PublishedTest'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Test'),
        ),
        migrations.AlterField(
            model_name='userunit',
            name='published_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.PublishedUnit'),
        ),
        migrations.AlterField(
            model_name='userunit',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Unit'),
        ),
        migrations.AlterField(
            model_name='userunit',
            name='user_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.UserClass'),
        ),
        migrations.AlterField(
            model_name='userunitobject',
            name='unit_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.PublishedUnitObject'),
        ),
        migrations.AlterField(
            model_name='userunitobject',
            name='user_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.UserUnit'),
        ),
    ]
