# Generated by Django 2.2.12 on 2021-03-07 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('randomtest', '0111_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MockTestFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MockTestObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=2)),
                ('instructions', models.CharField(max_length=1000)),
                ('time_limit', models.DurationField()),
                ('order', models.IntegerField(default=0)),
                ('mock_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mock_test_objects', to='mocktests.MockTest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MockTestProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('point_value', models.FloatField(default=1)),
                ('blank_point_value', models.FloatField(default=0)),
                ('answer_type', models.CharField(max_length=3)),
                ('units', models.CharField(max_length=50)),
                ('mocktest_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='randomtest.Problem')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='randomtest.Problem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserMockTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('mock_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mocktests.MockTest')),
                ('userprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mock_tests', to='randomtest.UserProfile')),
            ],
            options={
                'ordering': ['end_time'],
            },
        ),
        migrations.CreateModel(
            name='UserMockTestObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.IntegerField(default=0)),
                ('mock_test_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mocktests.MockTestObject')),
                ('user_mock_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mocktests.UserMockTest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserMockProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_a', models.CharField(default='', max_length=50)),
                ('answer_b', models.CharField(default='', max_length=50)),
                ('answer_c', models.CharField(default='', max_length=50)),
                ('correct', models.IntegerField(default=1)),
                ('points', models.FloatField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('mocktest_problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mocktests.MockTestProblem')),
                ('user_mocktest_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='mocktests.UserMockTestObject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='mocktest',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mock_tests', to='mocktests.MockTestFolder'),
        ),
    ]
