# Generated by Django 2.2.12 on 2021-03-07 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktestproblem',
            name='mocktest_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='mocktests.MockTestObject'),
        ),
    ]
