# Generated by Django 2.2.12 on 2021-03-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0002_auto_20210306_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktestobject',
            name='time_limit',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='usermocktest',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usermocktest',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usermocktestobject',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usermocktestobject',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
