# Generated by Django 2.2.12 on 2021-03-08 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0004_auto_20210308_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestproblem',
            name='mocktest_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='mocktests.MockTestSegment'),
        ),
        migrations.AddField(
            model_name='usermockproblem',
            name='user_mocktest_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='mocktests.UserMockTestSegment'),
        ),
        migrations.AddField(
            model_name='usermocktestsegment',
            name='mock_test_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mocktests.MockTestSegment'),
        ),
    ]
