# Generated by Django 2.2.12 on 2021-03-08 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0005_auto_20210308_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermocktestsegment',
            name='user_mock_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='mocktests.UserMockTest'),
        ),
    ]
