# Generated by Django 2.2.12 on 2021-03-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0006_auto_20210308_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermocktest',
            name='current_segment',
            field=models.IntegerField(default=0),
        ),
    ]
