# Generated by Django 2.2.12 on 2021-03-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0007_usermocktest_current_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermocktest',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usermocktest',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usermocktestsegment',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usermocktestsegment',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
