# Generated by Django 2.2.12 on 2021-04-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0008_auto_20210308_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermocktest',
            name='allow_solutions',
            field=models.BooleanField(default=0),
        ),
    ]
