# Generated by Django 2.2.12 on 2022-08-28 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0009_usermocktest_allow_solutions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.FloatField(default=0)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='mocktests.MockTestFolder')),
            ],
        ),
        migrations.CreateModel(
            name='MockTestSegmentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('segment_type', models.CharField(max_length=2)),
                ('instructions', models.CharField(max_length=1000)),
                ('time_limit', models.DurationField(null=True)),
                ('order', models.IntegerField(default=0)),
                ('problem_begin', models.IntegerField(default=0)),
                ('problem_end', models.IntegerField(default=0)),
                ('prefix', models.CharField(max_length=100)),
                ('point_value', models.FloatField(default=1)),
                ('blank_point_value', models.FloatField(default=0)),
                ('mock_test_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='mocktests.MockTestTemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
