from django.conf.urls import include#,url
from django.urls import path

from django.contrib.auth.decorators import login_required

from . import views
#from views import TestDelete

urlpatterns = [
    path('', views.splashview, name='splashview'),
    path('manage_accounts/', views.manage_accounts, name='manage_accounts'),
    path('randomtest/', views.tableview, name='tableview'),
    path('randomtest/createtest/', views.startform, name='startform'),
    path('randomtest/createtest/readme', views.readme, name='readme'),
    path('randomtest/test/<int:pk>/', views.testview, name='testview'),
    path('randomtest/test/<int:pk>/toggle_star/', views.toggle_star, name='toggle_star'),
    path('randomtest/test/<int:pk>/checkanswer/', views.checkanswer, name='checkanswer'),
    path('randomtest/test/<int:pk>/load_sol/<int:ppk>/', login_required(views.SolutionView.as_view()), name='load_solution'),
    path('randomtest/newtest/<int:pk>/', views.newtestview, name='newtestview'),
    path('randomtest/newtest/<int:pk>/toggle_star/', views.new_toggle_star, name='new_toggle_star'),
#    url(r'^newtest/(?P<pk>\d+)/checkanswer/$', views.checkanswer, name='checkanswer'),
    path('randomtest/newtest/<int:pk>/load_sol/<int:ppk>/', login_required(views.SolutionView.as_view()), name='load_solution'),
    path('randomtest/delete/<int:pk>/', views.deletetestresponses,name='test_delete'),
#    url(r'^edittest/(?P<pk>\d+)/$', views.testeditview,name='test_edit'),
    path('randomtest/viewlatex/<int:pk>/', views.latexview, name='view_latex'),
    path('randomtest/viewlatexsol/<int:pk>/', views.latexsolview, name='view_latex_sol'),
    path('randomtest/tagcounts/', views.tagcounts, name='tag_counts'),
    path('randomtest/pdftest/<int:pk>/', views.test_as_pdf,name='test_pdf'),
    path('randomtest/pdfsoltest/<int:pk>/', views.test_sol_as_pdf,name='test_sol_pdf'),
    path('randomtest/student/<str:username>/', views.tableview, name='studenttableview'),
    path('randomtest/student/<str:username>/addtest/<int:pk>/', views.addtestview, name='addstudenttestview'),
    path('randomtest/student/<str:username>/<int:pk>/', views.testview, name='studenttestview'),
    path('randomtest/student/<str:username>/viewlatex/<int:pk>/', views.latexview, name='view_latex'),
    path('randomtest/student/<str:username>/viewlatexsol/<int:pk>/', views.latexsolview, name='view_latex_sol'),
    path('randomtest/student/<str:username>/<int:pk>/load_sol/<int:ppk>/', login_required(views.SolutionView.as_view()), name='load_solution'),
    path('randomtest/student/<str:username>/archive/<int:tpk>/', views.archivestudentview, name='archivestudentview'),
    path('randomtest/student/<str:username>/unarchive/<int:tpk>/', views.unarchivestudentview, name='unarchivestudentview'),
    path('randomtest/student/<str:username>/delete/<int:pk>/', views.deletestudenttestresponses,name='test_delete'),
    path('randomtest/archive/<int:tpk>/', views.archiveview, name='archiveview'),
    path('randomtest/unarchive/<int:tpk>/', views.unarchiveview, name='unarchiveview'),
    path('randomtest/highscores/', views.highscore, name='highscoreview'),
    path('randomtest/highscores/<str:username>/', views.highscore, name='highscoreview'),
    path('randomtest/addfolder/<int:pk>/',views.addfolderview,name='addfolderview'),
    path('randomtest/addtest/<int:pk>/',views.addtestview,name='addtestview'),
    path('randomtest/urltest/',views.urltemptest,name='urltemptest'),
    path('randomtest/urltest/test',views.urltest,name='urltestview'),
    path('randomtest/urltest/latex', views.urllatexview, name='urlview_latex'),
    path('randomtest/urltest/latexsol', views.urllatexsolview, name='urlview_latex'),
    path('randomtest/profiles/<str:username>/',views.profileview,name='profileview'),
    path('randomtest/newcreatetest/', views.newstartform, name='startform2'),
    path('randomtest/editnewtest/<int:pk>/', views.editnewtestview, name='editnewtestview'),
    path('randomtest/edittimezone/',views.changetimezoneview,name='changetimezoneview'),
    path('randomtest/ajax/deletetest/',views.delete_usertest,name='delete_usertest'),
    path('randomtest/ajax/load-add-user/',views.load_add_user,name='load_add_user'),
    path('randomtest/ajax/add-user/',views.add_user,name='add_user'),
    path('randomtest/ajax/load-edit-user/',views.load_edit_user,name='load_edit_user'),
    path('randomtest/ajax/edit-user/',views.edit_user,name='edit_user'),
    path('collaborators/',views.managecollaborators,name='manage_collaborators'),
    path('collaborators/ajax/request-collaborator/',views.send_collab_request,name='request_collaborator'),
    path('collaborators/ajax/accept-request/',views.accept_request,name='accept_request'),
    path('collaborators/ajax/deny-request/',views.deny_request,name='deny_request'),
    path('collaborators/ajax/withdraw-request/',views.withdraw_request,name='withdraw_request'),
    path('collaborators/ajax/remove-collaborator/',views.remove_collaborator,name='remove_collaborator'),
    path('randomtest/pdfoptions/<int:pk>/', views.testpdfoptions, name='testpdfoptions'),
    path('randomtest/pdfoptions/<int:pk>/problems/', views.problempdf, name='problempdf'),
    path('randomtest/pdfoptions/<int:pk>/solutions/', views.solutionpdf, name='solutionpdf'),
    path('randomtest/pdfoptions/<int:pk>/answerkey/', views.answerkeypdf, name='answerkeypdf'),
]
