# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-26 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0004_auto_20170826_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='top_theorem_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='theorem',
            name='theorem_number',
            field=models.IntegerField(),
        ),
    ]
