# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-05 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0005_auto_20170826_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='documentelement',
            options={'ordering': ['order']},
        ),
    ]
