# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-05 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0006_auto_20170904_2354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageModel',
        ),
    ]
