# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-08 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0007_auto_20170905_0007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
