# Generated by Django 5.2.17 on 2026-08-26 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0011_auto_20231218_1743'),
        ('randomtest', '0123_alter_problem_duplicate_problems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProblemSet',
            new_name='HProblemSet',
        ),
        migrations.RenameModel(
            old_name='Proof',
            new_name='HProof',
        ),
        migrations.RenameModel(
            old_name='TextBlock',
            new_name='HTextBlock',
        ),
        migrations.RenameModel(
            old_name='Theorem',
            new_name='HTheorem',
        ),
    ]
